export const AUHTENTICATE_USER_START = "AUHTENTICATE_USER_START";
export const AUHTENTICATE_USER_SUCCESS = "AUHTENTICATE_USER_SUCCESS";
export const AUHTENTICATE_USER_FAILURE = "AUHTENTICATE_USER_FAILURE";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGOUT_USER_START = "LOGOUT_USER_START";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";

export const SET_STAY_SIGNED_IN = "SET_STAY_SIGNED_IN";
